[package]
name = "tokio_chat_server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
log = "0.4.26"
tokio = { version = "1.44.1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync",]}
